### ISSUE TITLE
Assigning custom commands to puck motion

### ISSUE THREAD

**Issue by jazweatherhead** [Lasse-B/Sx2vJoy#10]
Is there a way to assign custom commands to puck motion? Thx.

**Comment by Lasse-B** [comment]
Certainly possible. Instead of feeding axis movements to vJoy you can pretty much do whatever you want. It's however not the purpose of Sx2vJoy. It would require rewriting large portions of the code as well as giving the GUI an overhaul to build support for the increased scope of capabilities.
