### ISSUE TITLE
Please add support for the SpaceMouse Compact

### ISSUE THREAD

**Issue by TORUS-LABS** [Lasse-B/Sx2vJoy#13]
Unfortunately, the SpaceMouse Compact currently seems to not be supported which is a shame. Please, could you make it work on this model, too? :)

Thank you so much for your work!

**Comment by TilTisback** [comment]
I second this!

edit: i looked around in the source and it seems the id of the SpaceMouce compact is missing. so i searched on my computer and found that it is 9583 and 50741.
maybe it will help you implement it.
![spacemouse id](https://user-images.githubusercontent.com/13772017/56864214-1e082b80-69c0-11e9-86c7-8226b134f9d8.PNG)

**Comment by Lasse-B** [comment]
Added SpaceMouse Compact support to the test branch. you can find it here:
https://github.com/Lasse-B/Sx2vJoy-test
