### ISSUE TITLE
Sx2vJoy quits unexpectedly.

### ISSUE THREAD

**Issue by cowboy** [Lasse-B/Sx2vJoy#3]
I have no idea what's causing it, but sometimes Sx2vJoy  just quits. No error notice of any kind. I'm using v1.2 build 3.

Is there a way for it to log quit reasons to a file I can send you? Does it do anything like this already?

FWIW, this happened sometime during a jump, causing my ship to cruise directly into the target destination's sun. Whoops. Fortunately, I was able to kill the game process quickly enough to keep from losing everything.

``` ahk
; "oh shit"
!^+F8::WinClose Elite - Dangerous (CLIENT)
```

**Comment by Lasse-B** [comment]
You seem to be the first to have come across this as nobody from the E:D or SC forums has posted about yet.

Whenever Sx2vJoy quits through causes other than the process getting killed or the user closing it manually through the tray icon, it displays a message explaining why it has to close. As AutoHotkey is a scripting language, any errors in the script code would be caught and displayed by its interpreter that comes bundled with it. This leads me to believe that either something external killed Sx2vJoy, or it caused something external to kill it. Is there anything in the Windows log (Event Viewer -> Windows Logs -> Application)? I sure hope that dreaded heap corruption error (exception code 0xc0000374) isn't back.

**Comment by cowboy** [comment]
Yep, the error log shows `0xc0000374`.

``` txt
Faulting application name: Sx2vJoy.exe, version: 1.2.3.0, time stamp: 0x54276b33
Faulting module name: ntdll.dll, version: 6.3.9600.17278, time stamp: 0x53eeb4a3
Exception code: 0xc0000374
Fault offset: 0x000debd8
Faulting process id: 0x46b4
Faulting application start time: 0x01d02ed9a20b6e96
Faulting application path: C:\util\Sx2vJoy\Sx2vJoy.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: e401fa91-9acc-11e4-8268-3085a9991283
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Lasse-B** [comment]
Of course it couldn't have been anything different :p

I've put some research into it a couple of days ago. There's a quick and easy fix that worked for me, but I fear it might eventually cause other issues. I've updated Sx2vJoy to give it a shot though:

http://lbsoftware.bplaced.net/Sx2vJoy/Sx2vJoy_1.2_build_4_test_1.zip

**Comment by cowboy** [comment]
Thanks, I'll give it a try!

**Comment by Lasse-B** [comment]
Independently of the issue being fixed now or not, the scenario of losing one's in-game assets due to Sx2vJoy being involuntarily closed is something I haven't thought of before. For that reason I'm going to add watchdog functionality to the next release to automatically restart Sx2vJoy and auto-apply the settings from the previous session if it's found to be no longer running. Current response time is 100ms-ish which I find to be very good given a crash or termination scenario.

**Comment by cowboy** [comment]
I was thinking of asking for that, but was afraid you might not want to layer too many band-aids on top of this thing. Thanks!

**Comment by Lasse-B** [comment]
I much prefer fixing issues at their root, but in a scenario like yours where every split-second counts, a fix that takes time to implement is not an option.

Btw, how is build 4 test 1 working so far?

**Comment by cowboy** [comment]
I haven't had time to use it yet! Perhaps later today.

**Comment by Lasse-B** [comment]
I've seen it happen twice now with v1.2 build 3 and build 4 test 1 during the last week, however only when newly started programs opened their windows.

I changed some things yet again in build 4 test 4, which I'd like you to take out for a spin:
http://lbsoftware.bplaced.net/Sx2vJoy/Sx2vJoy_1.2_build_4_test_4.zip

Please let me know how it goes.

**Comment by cowboy** [comment]
Ok, I'm in the process of rebuilding my computer workstation, so it may be a few days before I get to this. Thanks, though. I'll give it a shot ASAP!

**Comment by Lasse-B** [comment]
Any news?

**Comment by cowboy** [comment]
Still rebuilding things. I'm aiming for getting back up and running for ED 1.2, but gaming is on the back burner for the moment!

**Comment by meta-meta** [comment]
I'm seeing this as well.  Windows 10 x64  actually happens on startup as in issue #9 

```
Faulting application name: Sx2vJoy.exe, version: 1.2.5.9, time stamp: 0x564320ba
Faulting module name: ntdll.dll, version: 10.0.10586.103, time stamp: 0x56a853dc
Exception code: 0xc0000374
Fault offset: 0x000dc759
Faulting process id: 0xce50
Faulting application start time: 0x01d169d720ff8a1b
Faulting application path: C:\Users\Paul\Downloads\Sx2vJoy-test-master\Sx2vJoy-test-master\Sx2vJoy.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: b7201a12-4f7f-4b40-85f0-f8b0ae449856
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Lasse-B** [comment]
Have you tried the test branch of Sx2vJoy?
https://github.com/Lasse-B/Sx2vJoy-test
