### ISSUE TITLE
Running two mice at once

### ISSUE THREAD

**Issue by Arhowk** [Lasse-B/Sx2vJoy#4]
Hi, I'm trying to run two spacenavigators at once emulating them both with sx2vjoy but if I try to plug the second one in, the vjoy profile flashes between the two space mice instead of having two profiles, one for each. I looked for support on the forum page but couldnt find anything. Your help would be greatly appreciated!

**Comment by Lasse-B** [comment]
Hey,

multiple devices with the same vendor and product IDs are not yet supported unfortunately. This and more is on my to-do list for the next larger update, but at the moment I don't have a whole lot of time to spend on the project.

Sorry I don't have more cheerful news :(
