### ISSUE TITLE
couldn't load vjoyinterface.dll

### ISSUE THREAD

**Issue by Aruee** [Lasse-B/Sx2vJoy#7]
My setup is a little exotic, but I thought I may ask for help anyway...

Running Windows 10 TP Build 9926 in WinToGo mode off an external drive to play some Windows only games. Thought I'd run E:D with my old SpacePilot... but couldn't really get any joystick input working. Sx2vJoy crashes in all compatibility modes and running as admin or not, each time issuing the above error message. Any idea?

Thanks in advance.

**Comment by Lasse-B** [comment]
All I can say in regard to Win10 is that Sx2vJoy worked just fine on build 10036, which I was given the opportunity to test on for one evening.

To my knowledge, as of this posting the most current build of Win10 is 10041. Give it a try, I'm almost certain it'll work. If there is such a thing as certainty when it comes to an operating system that's still under heavy construction.

**Comment by Aruee** [comment]
Sorry for taking so long... I'm now running a Win 8.1 to go installation, everything works just fine. Thanks anyway :)
