### ISSUE TITLE
Sx2vJoy.exe: Crash on start up

### ISSUE THREAD

**Issue by arthurp** [Lasse-B/Sx2vJoy#9]
The program crashed just after it started. The tray icon does appear. The only debug information I could see is the following. I don't have a dev environment of any kind on my Windows install (I only use it for games), so I cannot really produce much more.

This is on Windows 7 (64-bit) using the latest vJoy (2.1.6) and 3dxware (10.3.0).

Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: Sx2vJoy.exe
  Application Version:  1.2.4.0
  Application Timestamp:    54276b33
  Fault Module Name:    StackHash_d851
  Fault Module Version: 6.1.7601.17725
  Fault Module Timestamp:   4ec49b8f
  Exception Code:   c0000374
  Exception Offset: 000ce6c3
  OS Version:   6.1.7601.2.1.0.256.1
  Locale ID:    1033
  Additional Information 1: d851
  Additional Information 2: d8513f82e00e17d2f00f0998f9540641
  Additional Information 3: d34b
  Additional Information 4: d34bb11e82fddbf692bccc25d25295bb

**Comment by B4ckBone** [comment]
Same here. Im on Windows 10 using a Space Mouse Pro wired edition.
I have vjoy installed. Eset antivirus is running. And the latest 3Dconnexion drivers installed.

**Comment by B4ckBone** [comment]
Never mind .. testing branch v1.2 build 5 test 9 works nice with my steup!
Keep up the good work! 
Thanks m8
